import fsSync from 'fs';
import path from 'path';
import color from 'picocolors';
import { intro, outro } from '@clack/prompts';
import { trackSuccess } from '../core/telemetry.js';
import { failCommand, failProjectNotInitialized } from '../utils/command.js';
import { parseFlags, normalizeOptions, normalizeArgv } from '../utils/args.js';
import { resolveRegion, resolveProjectName, resolveCwd, readFileSafe, readTerraformComputeTarget } from '../utils/resolvers.js';

export const ALERTS_TF_FILE = path.join('terraform', 'alerts.tf');

export function parseAlertsArgs(argv = []) {
    const args = normalizeArgv(argv);
    if (args[0] === 'alerts') args.shift();
    const { options, rest } = parseFlags(args, {
        string: ['region', 'project-name'],
        boolean: ['force'],
    });
    const positionals = rest.filter((arg) => typeof arg === 'string' && !arg.startsWith('-'));
    if (positionals.length > 0) options.unexpectedPositionals = positionals;
    return options;
}

// SNS topic + 5xx notify alarm. Thresholds mirror the dashboard alarm in
// templates/terraform/main.tf (`alb_5xx_errors`); the alarm name differs
// (`-5xx-notify`) so the notifying alarm is distinguishable from it.
export function buildAlertsTf({ projectName }) {
    return `# Grada alert notifications (generated by \`grada alerts\`).
# Subscribe an email address after apply:
#   aws sns subscribe --topic-arn <topic-arn> --protocol email \\
#     --notification-endpoint you@example.com
# then click the confirmation link. Raw Slack/Discord webhook URLs cannot
# confirm SNS subscriptions, so they need a forwarding Lambda (not yet
# generated) — email works end to end today.

resource "aws_sns_topic" "alerts" {
  name = "${projectName}-alerts"
}

resource "aws_cloudwatch_metric_alarm" "notify_5xx" {
  alarm_name          = "${projectName}-5xx-notify"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = "2"
  metric_name         = "HTTPCode_Target_5XX_Count"
  namespace           = "AWS/ApplicationELB"
  period              = "60"
  statistic           = "Sum"
  threshold           = "10"
  alarm_description   = "Notifies ${projectName}-alerts when the ALB serves more than 10 5XX errors in 2 minutes."

  alarm_actions = [aws_sns_topic.alerts.arn]

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
  }
}
`;
}

export async function runAlerts(input = {}) {
    const options = normalizeOptions(input);
    let cwd;
    let region;
    let projectName;
    try {
        cwd = resolveCwd(options);
        region = resolveRegion(options, cwd);
        projectName = resolveProjectName(options, cwd);
    } catch {
        return failProjectNotInitialized({ event: 'alerts_run' });
    }
    const force = options.force === true || options.force === 'true';

    intro(color.bgCyan(color.black(' grada alerts 🔔 ')));

    if (Array.isArray(options.unexpectedPositionals) && options.unexpectedPositionals.length > 0) {
        return failCommand({
            message: `\n✖ Unexpected argument "${options.unexpectedPositionals[0]}". Run "grada alerts" to scaffold notifications.\n`,
            event: 'alerts_run',
            telemetry: { projectName },
            errorCode: 'UNEXPECTED_POSITIONAL_ARGS',
            reason: 'unexpected-positional-args',
            resultExtra: { region },
        });
    }

    const target = readTerraformComputeTarget(cwd);
    if (target !== 'ecs') {
        return failCommand({
            message: `\n✖ Alert scaffolding currently supports ECS projects only (detected target: ${target}).\n`,
            hint: '  Lambda and static targets have no ALB to alarm on yet.\n',
            event: 'alerts_run',
            telemetry: { projectName },
            errorCode: 'ALERTS_TARGET_UNSUPPORTED',
            reason: 'alerts-target-unsupported',
            resultExtra: { region },
        });
    }

    const mainTf = readFileSafe(path.join(cwd, 'terraform', 'main.tf'));
    if (!mainTf) {
        return failCommand({
            message: '\n✖ No terraform/main.tf found. Run "grada" first before scaffolding alerts.\n',
            event: 'alerts_run',
            telemetry: { projectName },
            errorCode: 'TERRAFORM_NOT_INITIALIZED',
            reason: 'terraform-not-initialized',
            resultExtra: { region },
        });
    }
    if (!mainTf.includes('resource "aws_lb" "main"')) {
        return failCommand({
            message: '\n✖ No aws_lb.main resource found in terraform/main.tf — the 5xx alarm has nothing to attach to.\n',
            hint: '  If you ejected or heavily customized the stack, wire aws_sns_topic manually.\n',
            event: 'alerts_run',
            telemetry: { projectName },
            errorCode: 'ALB_NOT_FOUND',
            reason: 'alb-not-found',
            resultExtra: { region },
        });
    }

    const alertsPath = path.join(cwd, ALERTS_TF_FILE);
    if (fsSync.existsSync(alertsPath) && !force) {
        return failCommand({
            message: `\n⚠ ${ALERTS_TF_FILE} already exists. Pass --force to overwrite.\n`,
            tone: 'yellow',
            event: 'alerts_run',
            telemetry: { projectName, error_code: 'ALERTS_FILE_EXISTS' },
            reason: 'alerts-file-exists',
            resultExtra: { projectName, region },
            exitCode: null,
        });
    }

    fsSync.writeFileSync(alertsPath, buildAlertsTf({ projectName }));
    console.log(color.green(`\n✅ Created ${ALERTS_TF_FILE} (SNS topic + 5xx notify alarm).`));
    console.log(color.dim('  Next steps:'));
    console.log(color.dim('    1. npx grada-run apply'));
    console.log(color.dim(`    2. aws sns subscribe --topic-arn <topic-arn> --protocol email --notification-endpoint you@example.com --region ${region}`));
    console.log(color.dim('    3. Click the confirmation link in the email.\n'));
    await trackSuccess('alerts_run', { projectName, action: 'scaffold' });
    outro(color.green('Done.'));
    return { ok: true, action: 'scaffold', projectName, region, file: ALERTS_TF_FILE };
}
