import path from 'path';
import fs from 'fs';
import { intro, outro, spinner, log, cancel, confirm } from '@clack/prompts';
import color from 'picocolors';
import { renderDryRunPreview, parseTerraformConfig, buildCostTelemetryProps } from '../utils/visualizer.js';
import { detectFramework } from '../utils/detector.js';
import { trackEvent, flushTelemetry, trackSuccess, trackFailure } from '../core/telemetry.js';
import { failCommand, shouldAutoApprove } from '../utils/command.js';
import { parseFlags, normalizeOptions, normalizeArgv } from '../utils/args.js';
import { spawnSync } from 'child_process';
import { runTerraformCommand, getTerraformOutputs } from '../utils/terraform.js';
import { requireAwakeEnvironment, resolveSleepTarget } from '../utils/sleep-state.js';
import { promptStateBucketRecovery, recreateStateBucket } from '../utils/recovery.js';
import { resolveProjectName } from '../utils/resolvers.js';
import { ensureLambdaSeedImage } from '../utils/lambda-ecr.js';
import { runWake } from './wake.js';

export function parseApplyArgs(argv = []) {
    const args = normalizeArgv(argv);
    if (args[0] === 'apply' || args[0] === 'deploy') args.shift();
    const { options } = parseFlags(args, {
        boolean: ['force'],
    });
    return { force: false, ...options };
}

export async function applyStack(input = {}) {
    const options = normalizeOptions(input);
    intro(color.bgCyan(color.black(' grada apply ☁️  ')));

    const targetDir = process.cwd();
    const tfDir = path.join(targetDir, 'terraform');

    // 1. Verify that the user is inside a project generated by grada
    if (!fs.existsSync(tfDir) || !fs.existsSync(path.join(tfDir, 'main.tf'))) {
        return failCommand({
            print: () => {
                log.error(color.red('✖ No terraform directory found in current path.'));
                log.message('Please run "npx grada-run" first to generate your infrastructure templates.');
            },
        });
    }

    // 1b. Refuse to apply against an asleep environment: apply resets
    // the app desired count while the database stays stopped, so fresh
    // tasks would crash-loop. Headless fails fast; interactive offers to
    // wake first; --force proceeds with the override in telemetry.
    const sleepTarget = resolveSleepTarget({}, targetDir);
    const asleepEntry = requireAwakeEnvironment(targetDir, sleepTarget.envKey);
    if (asleepEntry) {
        // Dry runs change nothing, so they keep the historical advisory
        // warning instead of the gate below.
        if (options.isDryRun) {
            log.warn(color.yellow(`⚠ Environment "${sleepTarget.envKey}" is asleep. This preview changes nothing; run ${color.green('npx grada-run wake')} before a real apply.`));
        } else if (options.force === true || options.force === 'true') {
            log.warn(color.yellow(`⚠ Environment "${sleepTarget.envKey}" is asleep and --force was passed. Tasks will start against a stopped database until you run ${color.green('npx grada-run wake')}.`));
            trackEvent('forced_apply_while_asleep', {
                projectName: path.basename(targetDir),
                env: sleepTarget.envKey,
            });
            await flushTelemetry();
        } else if (shouldAutoApprove(options)) {
            return failCommand({
                message: `\n✖ Environment "${sleepTarget.envKey}" is asleep. Apply would start tasks against a stopped database.`,
                hint: `  Run npx grada-run wake first, or re-run with --force to proceed anyway.\n`,
                event: 'infrastructure_applied',
                telemetry: { projectName: path.basename(targetDir) },
                errorCode: 'SLEEPING_ENVIRONMENT',
                reason: 'sleeping-environment',
                resultExtra: { env: sleepTarget.envKey },
            });
        } else {
            const wakeFirst = await confirm({
                message: `Environment "${sleepTarget.envKey}" is asleep. Wake it now and continue with apply?`,
                initialValue: true,
            });
            if (wakeFirst !== true) {
                cancel('Apply aborted. The environment is still asleep.');
                return { ok: false, reason: 'cancelled', env: sleepTarget.envKey };
            }
            const wakeImpl = options.wakeImpl || runWake;
            const woken = await wakeImpl({ cwd: targetDir, env: sleepTarget.envKey });
            if (!woken || woken.ok !== true) {
                return failCommand({
                    message: '\n✖ Wake did not complete — apply aborted.',
                    hint: '  Resolve the wake failure, then re-run apply.\n',
                    event: 'infrastructure_applied',
                    telemetry: { projectName: path.basename(targetDir) },
                    errorCode: 'WAKE_FAILED',
                    reason: 'wake-failed',
                    resultExtra: { env: sleepTarget.envKey, wakeReason: woken?.reason ?? null },
                });
            }
        }
    }

    // 2. Read the actual AWS configuration from disk (CPU, Memory, Region, Database)
    const detectedConfig = parseTerraformConfig(tfDir);
    detectedConfig.projectName = path.basename(process.cwd());
    const costProps = buildCostTelemetryProps(detectedConfig);

    // 3. Detect the framework name using your existing detector
    const detectedFw = detectFramework(targetDir);
    detectedConfig.framework = detectedFw ? detectedFw.name : 'Container';

    // 4. Run the visualizer (passing the flag so it knows whether to prompt)
    if (options.isDryRun) {
        await renderDryRunPreview(detectedConfig, true);
        outro(color.green('Dry run complete. No infrastructure was provisioned.'));
        await trackSuccess('infrastructure_dry_run', {
            framework: detectedConfig.framework,
            ...costProps,
        });
        process.exit(0);
    } else if (shouldAutoApprove(options)) {
        await renderDryRunPreview(detectedConfig, true);
    } else {
        const confirmed = await renderDryRunPreview(detectedConfig, false);
        if (!confirmed) {
            cancel('Apply aborted.');
            process.exit(0);
        }
    }

    const s = spinner();
    const runTerraform = options.runTerraformImpl || runTerraformCommand;
    const runSync = options.spawnSyncImpl || spawnSync;

    try {
        // 5. Run terraform init
        s.start('Initializing Terraform plugins...');
        await runTerraform(['init', '-upgrade'], tfDir, s, 'Initializing');
        s.stop('Terraform initialized.');

        // 5b. Lambda Day-0 bootstrap: CreateFunction rejects an empty ECR
        // repository, so ensure the repository exists and seed a minimal
        // placeholder image when :latest hasn't been pushed yet. No-op on
        // reruns once CI owns the tag.
        if (detectedConfig.computeTarget === 'lambda') {
            s.start('Ensuring ECR repository for the Lambda image...');
            await runTerraform(['apply', '-target=aws_ecr_repository.app', '-input=false', '-auto-approve'], tfDir, s, 'Ensuring ECR repository');
            s.stop('ECR repository ready.');

            s.start('Checking for a deployable container image...');
            const seed = ensureLambdaSeedImage({
                run: runSync,
                repository: `${resolveProjectName({}, targetDir)}-repo`,
                region: detectedConfig.region,
            });
            if (!seed.ok) {
                if (seed.reason === 'cli-missing') {
                    throw new Error('AWS CLI is required to bootstrap the Lambda container image on Day 0 (install it from https://aws.amazon.com/cli/, then re-run apply).');
                }
                throw new Error(`Could not bootstrap the Day-0 Lambda container image (${seed.reason}${seed.detail ? `: ${seed.detail}` : ''}). Push any image to ECR and re-run apply.`);
            }
            s.stop(seed.seeded ? 'Day-0 placeholder image seeded.' : 'Container image already present.');
        }

        // 6. Run terraform apply
        s.start('Provisioning AWS infrastructure (this may take 3–5 minutes)...');
        await runTerraform(['apply', '-auto-approve'], tfDir, s, 'Provisioning');
        s.stop('Cloud resources provisioned.');

        // 7. Extract and print the outputs
        const outputs = await getTerraformOutputs(tfDir);

        const cfUrl = outputs.cloudfront_url?.value;
        const albUrl = outputs.alb_direct_url?.value;
        const apiUrl = outputs.api_gateway_url?.value;
        const siteUrl = outputs.site_url?.value;

        let finalMessage = color.green('✅ Infrastructure is live!');
        if (cfUrl) finalMessage += `\n  🌍 App URL: ${color.cyan(cfUrl)} ${color.dim('(global CDN — share this link)')}`;
        if (albUrl) finalMessage += `\n  🚦 Direct URL: ${color.gray(albUrl)} ${color.dim('(bypasses the CDN — for debugging)')}`;
        if (apiUrl) finalMessage += `\n  🔌 API URL: ${color.gray(apiUrl)} ${color.dim('(bypasses the CDN — for debugging)')}`;
        if (siteUrl) finalMessage += `\n  🌍 Site URL: ${color.cyan(siteUrl)} ${color.dim('(global CDN — share this link)')}`;

        outro(`${finalMessage}\n\n  ${color.yellow('Push code to deploy your app and clear the 503 error:')}\n  ${color.cyan('git add . && git commit -m "ci: infra" && git push origin main')}`);

        const actualProjectName = path.basename(process.cwd());
        await trackSuccess('infrastructure_applied', {
            projectName: actualProjectName,
            framework: detectedConfig.framework,
            ...costProps
        });

        process.exit(0);

    } catch (error) {
        s.stop(color.red('❌ Terraform apply failed.'));

        const errString = error.message || "";

        if (errString.includes('NoSuchBucket') || errString.includes('does not exist')) {
            log.warn('Terraform state bucket is missing (likely deleted manually or via destroy).');

            trackEvent('recovery_prompted', { type: 'state_bucket_missing' });

            const shouldRecreate = await promptStateBucketRecovery({ autoApprove: shouldAutoApprove(options) });

            if (!shouldRecreate) {
                return failCommand({
                    print: () => cancel('Apply aborted. State bucket remains missing.'),
                    event: 'recovery_declined',
                    telemetry: { type: 'state_bucket_missing' },
                });
            }

            trackEvent('recovery_accepted', { type: 'state_bucket_missing' });

            try {
                const actualProjectName = path.basename(process.cwd());
                const targetRegion = detectedConfig.region || process.env.AWS_REGION || 'us-east-2';

                const recSpinner = spinner();
                recSpinner.start('Recreating S3 state bucket in AWS...');
                await recreateStateBucket({ tfDir, region: targetRegion, projectName: actualProjectName });
                recSpinner.stop('✅ State bucket recreated.');

                trackEvent('recovery_successful', { type: 'state_bucket_missing' });

                // 3. Auto-resume the apply flow
                log.message(color.cyan('Resuming infrastructure provisioning...'));
                return applyStack({ ...options, autoApprove: true });

            } catch (recoveryErr) {
                return failCommand({
                    print: () => {
                        log.error(color.red('✖ Failed to auto-recover state bucket.'));
                        log.message(recoveryErr.message || recoveryErr);
                    },
                    event: 'recovery_failed',
                    telemetry: { type: 'state_bucket_missing', error: recoveryErr.message },
                });
            }
        } else if (errString.includes('EntityAlreadyExists') && errString.includes('token.actions.githubusercontent.com')) {
            log.error(color.red('GitHub OIDC Provider Conflict Detected'));
            log.message('AWS only allows one GitHub Actions provider per account, and you already have one configured.');
            log.message('');
            log.message(`${color.bold('How to fix this:')}`);
            log.message(`1. Open ${color.cyan('terraform/oidc.tf')}`);
            log.message(`2. Change ${color.green('create_oidc_provider = true')} to ${color.green('create_oidc_provider = false')}`);
            log.message(`3. Run ${color.cyan('npx grada-run apply')} again.`);
        } else {
            // Generic fallback for unknown errors
            log.error(color.red(errString));
            log.message(`${color.bold('To debug manually, navigate to your terraform folder:')}`);
            log.message(color.cyan('cd terraform && terraform apply'));
        }

        const actualProjectName = path.basename(process.cwd());
        await trackFailure('infrastructure_applied', {
            projectName: actualProjectName,
            error_code: error.code || 'UNKNOWN',
            ...costProps
        });

        return failCommand({ exitCode: 1 });
    }
}