import path from 'path';
import fs from 'fs';
import { intro, outro, spinner, log, cancel, confirm, isCancel } from '@clack/prompts';
import color from 'picocolors';
import { renderDryRunPreview, parseTerraformConfig, buildCostTelemetryProps } from '../utils/visualizer.js';
import { detectFramework } from '../utils/detector.js';
import { trackEvent, flushTelemetry, trackSuccess, trackFailure } from '../core/telemetry.js';
import { failCommand, shouldAutoApprove } from '../utils/command.js';
import { normalizeOptions } from '../utils/args.js';
import { spawnSync } from 'child_process';
import { provisionStateBucket } from '../utils/aws.js';
import { runTerraformCommand, getTerraformOutputs } from '../utils/terraform.js';
import { readSleepState, resolveSleepTarget } from '../utils/sleep-state.js';
import { resolveProjectName } from '../utils/resolvers.js';
import { ensureLambdaSeedImage } from '../utils/lambda-ecr.js';

export async function applyStack(input = {}) {
    const options = normalizeOptions(input);
    intro(color.bgCyan(color.black(' grada apply ☁️  ')));

    const targetDir = process.cwd();
    const tfDir = path.join(targetDir, 'terraform');

    // 1. Verify that the user is inside a project generated by grada
    if (!fs.existsSync(tfDir) || !fs.existsSync(path.join(tfDir, 'main.tf'))) {
        return failCommand({
            print: () => {
                log.error(color.red('✖ No terraform directory found in current path.'));
                log.message('Please run "npx grada-run" first to generate your infrastructure templates.');
            },
        });
    }

    // 1b. Warn when this environment is asleep: apply resets the app
    // desired count while the database stays stopped, so fresh tasks would
    // crash-loop. Advisory only — the apply still proceeds.
    const sleepState = readSleepState(targetDir);
    const sleepTarget = resolveSleepTarget({}, targetDir);
    if (sleepState[sleepTarget.envKey]) {
        log.warn(color.yellow(`⚠ Environment "${sleepTarget.envKey}" is asleep. Run ${color.green('npx grada-run wake')} first, or this apply will start tasks against a stopped database.`));
    }

    // 2. Read the actual AWS configuration from disk (CPU, Memory, Region, Database)
    const detectedConfig = parseTerraformConfig(tfDir);
    detectedConfig.projectName = path.basename(process.cwd());
    const costProps = buildCostTelemetryProps(detectedConfig);

    // 3. Detect the framework name using your existing detector
    const detectedFw = detectFramework(targetDir);
    detectedConfig.framework = detectedFw ? detectedFw.name : 'Container';

    // 4. Run the visualizer (passing the flag so it knows whether to prompt)
    if (options.isDryRun) {
        await renderDryRunPreview(detectedConfig, true);
        outro(color.green('Dry run complete. No infrastructure was provisioned.'));
        await trackSuccess('infrastructure_dry_run', {
            framework: detectedConfig.framework,
            ...costProps,
        });
        process.exit(0);
    } else if (shouldAutoApprove(options)) {
        await renderDryRunPreview(detectedConfig, true);
    } else {
        const confirmed = await renderDryRunPreview(detectedConfig, false);
        if (!confirmed) {
            cancel('Apply aborted.');
            process.exit(0);
        }
    }

    const s = spinner();
    const runTerraform = options.runTerraformImpl || runTerraformCommand;
    const runSync = options.spawnSyncImpl || spawnSync;

    try {
        // 5. Run terraform init
        s.start('Initializing Terraform plugins...');
        await runTerraform(['init', '-upgrade'], tfDir, s, 'Initializing');
        s.stop('Terraform initialized.');

        // 5b. Lambda Day-0 bootstrap: CreateFunction rejects an empty ECR
        // repository, so ensure the repository exists and seed a minimal
        // placeholder image when :latest hasn't been pushed yet. No-op on
        // reruns once CI owns the tag.
        if (detectedConfig.computeTarget === 'lambda') {
            s.start('Ensuring ECR repository for the Lambda image...');
            await runTerraform(['apply', '-target=aws_ecr_repository.app', '-input=false', '-auto-approve'], tfDir, s, 'Ensuring ECR repository');
            s.stop('ECR repository ready.');

            s.start('Checking for a deployable container image...');
            const seed = ensureLambdaSeedImage({
                run: runSync,
                repository: `${resolveProjectName({}, targetDir)}-repo`,
                region: detectedConfig.region,
            });
            if (!seed.ok) {
                if (seed.reason === 'cli-missing') {
                    throw new Error('AWS CLI is required to bootstrap the Lambda container image on Day 0 (install it from https://aws.amazon.com/cli/, then re-run apply).');
                }
                throw new Error(`Could not bootstrap the Day-0 Lambda container image (${seed.reason}${seed.detail ? `: ${seed.detail}` : ''}). Push any image to ECR and re-run apply.`);
            }
            s.stop(seed.seeded ? 'Day-0 placeholder image seeded.' : 'Container image already present.');
        }

        // 6. Run terraform apply
        s.start('Provisioning AWS infrastructure (this may take 3–5 minutes)...');
        await runTerraform(['apply', '-auto-approve'], tfDir, s, 'Provisioning');
        s.stop('Cloud resources provisioned.');

        // 7. Extract and print the outputs
        const outputs = await getTerraformOutputs(tfDir);

        const cfUrl = outputs.cloudfront_url?.value;
        const albUrl = outputs.alb_direct_url?.value;
        const apiUrl = outputs.api_gateway_url?.value;
        const siteUrl = outputs.site_url?.value;

        let finalMessage = color.green('✅ Infrastructure is live!');
        if (cfUrl) finalMessage += `\n  🌍 App URL: ${color.cyan(cfUrl)} ${color.dim('(global CDN — share this link)')}`;
        if (albUrl) finalMessage += `\n  🚦 Direct URL: ${color.gray(albUrl)} ${color.dim('(bypasses the CDN — for debugging)')}`;
        if (apiUrl) finalMessage += `\n  🔌 API URL: ${color.gray(apiUrl)} ${color.dim('(bypasses the CDN — for debugging)')}`;
        if (siteUrl) finalMessage += `\n  🌍 Site URL: ${color.cyan(siteUrl)} ${color.dim('(global CDN — share this link)')}`;

        outro(`${finalMessage}\n\n  ${color.yellow('Push code to deploy your app and clear the 503 error:')}\n  ${color.cyan('git add . && git commit -m "ci: infra" && git push origin main')}`);

        const actualProjectName = path.basename(process.cwd());
        await trackSuccess('infrastructure_applied', {
            projectName: actualProjectName,
            framework: detectedConfig.framework,
            ...costProps
        });

        process.exit(0);

    } catch (error) {
        s.stop(color.red('❌ Terraform apply failed.'));

        const errString = error.message || "";

        if (errString.includes('NoSuchBucket') || errString.includes('does not exist')) {
            log.warn('Terraform state bucket is missing (likely deleted manually or via destroy).');

            trackEvent('recovery_prompted', { type: 'state_bucket_missing' });

            const shouldRecreate = shouldAutoApprove(options) ? true : await confirm({
                message: 'Do you want to automatically recreate the state bucket and resume provisioning?',
                initialValue: true
            });

            if (isCancel(shouldRecreate) || !shouldRecreate) {
                return failCommand({
                    print: () => cancel('Apply aborted. State bucket remains missing.'),
                    event: 'recovery_declined',
                    telemetry: { type: 'state_bucket_missing' },
                });
            }

            trackEvent('recovery_accepted', { type: 'state_bucket_missing' });

            try {
                // 1. Destroy corrupted local cache
                const dotTerraformPath = path.join(tfDir, '.terraform');
                if (fs.existsSync(dotTerraformPath)) {
                    fs.rmSync(dotTerraformPath, { recursive: true, force: true });
                }

                // 2. Recreate bucket
                const actualProjectName = path.basename(process.cwd());
                const targetRegion = detectedConfig.region || process.env.AWS_REGION || 'us-east-2';

                const recSpinner = spinner();
                recSpinner.start('Recreating S3 state bucket in AWS...');
                await provisionStateBucket(targetRegion, actualProjectName);
                recSpinner.stop('✅ State bucket recreated.');

                trackEvent('recovery_successful', { type: 'state_bucket_missing' });

                // 3. Auto-resume the apply flow
                log.message(color.cyan('Resuming infrastructure provisioning...'));
                return applyStack({ ...options, autoApprove: true });

            } catch (recoveryErr) {
                return failCommand({
                    print: () => {
                        log.error(color.red('✖ Failed to auto-recover state bucket.'));
                        log.message(recoveryErr.message || recoveryErr);
                    },
                    event: 'recovery_failed',
                    telemetry: { type: 'state_bucket_missing', error: recoveryErr.message },
                });
            }
        } else if (errString.includes('EntityAlreadyExists') && errString.includes('token.actions.githubusercontent.com')) {
            log.error(color.red('GitHub OIDC Provider Conflict Detected'));
            log.message('AWS only allows one GitHub Actions provider per account, and you already have one configured.');
            log.message('');
            log.message(`${color.bold('How to fix this:')}`);
            log.message(`1. Open ${color.cyan('terraform/oidc.tf')}`);
            log.message(`2. Change ${color.green('create_oidc_provider = true')} to ${color.green('create_oidc_provider = false')}`);
            log.message(`3. Run ${color.cyan('npx grada-run apply')} again.`);
        } else {
            // Generic fallback for unknown errors
            log.error(color.red(errString));
            log.message(`${color.bold('To debug manually, navigate to your terraform folder:')}`);
            log.message(color.cyan('cd terraform && terraform apply'));
        }

        const actualProjectName = path.basename(process.cwd());
        await trackFailure('infrastructure_applied', {
            projectName: actualProjectName,
            error_code: error.code || 'UNKNOWN',
            ...costProps
        });

        return failCommand({ exitCode: 1 });
    }
}