# grada addon: db:redis
# Generated by `grada add db:redis`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: fixed ~$9.49/mo baseline (cache.t4g.micro Valkey 8.0 at $0.013/hr
# in us-east-2); $0 intra-AZ VPC data transfer.

# --- ElastiCache Subnet Group ---
resource "aws_elasticache_subnet_group" "redis" {
  name       = "${local.app_name}-redis-subnets"
  subnet_ids = aws_subnet.public[*].id
}

# --- Redis Security Group (ECS tasks only) ---
resource "aws_security_group" "redis" {
  name        = "${local.app_name}-redis-sg"
  description = "Allow Redis/Valkey traffic strictly from ECS tasks"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [aws_security_group.ecs_tasks.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    # trivy:ignore:AVD-AWS-0104 - Allow cache nodes to reach standard AWS services
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- ElastiCache for Valkey Replication Group ---
# Valkey requires aws_elasticache_replication_group even for a single node:
# the aws_elasticache_cluster API rejects engine = "valkey".
# trivy:ignore:AVD-AWS-0045 - At-rest encryption disabled as a cost-saving trade-off for non-sensitive cache data
# trivy:ignore:AVD-AWS-0051 - Transit encryption disabled as a cost-saving trade-off for single-AZ cache traffic
resource "aws_elasticache_replication_group" "redis" {
  # replication_group_id allows at most 40 chars and must start with a letter.
  # The ds- prefix guarantees a leading letter and the md5 suffix keeps
  # default and PR-preview workspaces unique.
  replication_group_id       = "ds-${trim(substr(replace(lower(local.app_name), "/[^a-z0-9-]+/", "-"), 0, 5), "-")}-${substr(md5(local.app_name), 0, 5)}-redis"
  description                = "Valkey cache for ${local.app_name}"
  engine                     = "valkey"
  engine_version             = "8.0"
  node_type                  = "cache.t4g.micro"
  num_cache_clusters         = 1
  parameter_group_name       = "default.valkey8"
  port                       = 6379
  subnet_group_name          = aws_elasticache_subnet_group.redis.name
  security_group_ids         = [aws_security_group.redis.id]
  automatic_failover_enabled = false
  tags                       = { Name = "${local.app_name}-redis" }
}

# --- Outputs ---
output "redis_endpoint" {
  value = "redis://${aws_elasticache_replication_group.redis.primary_endpoint_address}:${aws_elasticache_replication_group.redis.port}"
}

output "redis_port" {
  value = aws_elasticache_replication_group.redis.port
}
