# grada addon: storage:s3
# Generated by `grada add storage:s3`. Do not edit by hand unless
# you know what you are doing — re-running with --force overwrites this file.
#
# Billing: no fixed hourly instance cost (usage-billed). S3 storage
# ($0.023/GB-mo), S3 PUT/GET requests, and CloudFront data transfer out
# are billed by usage on top of the stack's fixed baseline.

data "aws_caller_identity" "current" {}

# --- Private S3 Bucket ---
resource "aws_s3_bucket" "storage" {
  # Truncate and sanitize the prefix so the full account ID suffix always fits
  # within S3's 63-character limit. Underscores are replaced because S3 names
  # must be DNS-compatible (lowercase, hyphens only).
  bucket = "${trimsuffix(substr(replace(lower(local.app_name), "_", "-"), 0, 42), "-")}-storage-${data.aws_caller_identity.current.account_id}"
}

resource "aws_s3_bucket_public_access_block" "storage" {
  bucket                  = aws_s3_bucket.storage.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# trivy:ignore:AVD-AWS-0132 - Using free AES256 instead of Customer Managed Keys as a cost-saving trade-off
resource "aws_s3_bucket_server_side_encryption_configuration" "storage" {
  bucket = aws_s3_bucket.storage.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_cors_configuration" "storage" {
  bucket = aws_s3_bucket.storage.id

  cors_rule {
    allowed_methods  = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    # NOTE: intentionally open for zero-config presigned browser uploads.
    # Restrict to your app domain (e.g. ["https://example.com"]) once known.
    allowed_origins  = ["*"]
    allowed_headers  = ["*"]
    expose_headers   = ["ETag"]
    max_age_seconds  = 3000
  }
}

# --- CloudFront Distribution with Origin Access Control ---
resource "aws_cloudfront_origin_access_control" "storage_oac" {
  name                              = "${local.app_name}-storage-oac"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# trivy:ignore:AVD-AWS-0011 - WAF is omitted by default to prevent unexpected monthly costs for users
resource "aws_cloudfront_distribution" "storage_cdn" {
  enabled             = true
  is_ipv6_enabled     = true
  wait_for_deployment = false

  origin {
    domain_name              = aws_s3_bucket.storage.bucket_regional_domain_name
    origin_id                = "S3Origin"
    origin_access_control_id = aws_cloudfront_origin_access_control.storage_oac.id
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "S3Origin"
    viewer_protocol_policy = "redirect-to-https"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}

resource "aws_s3_bucket_policy" "storage_oac_policy" {
  bucket = aws_s3_bucket.storage.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowCloudFrontOAC"
        Effect    = "Allow"
        Principal = { Service = "cloudfront.amazonaws.com" }
        Action    = "s3:GetObject"
        Resource  = "${aws_s3_bucket.storage.arn}/*"
        Condition = {
          StringEquals = { "AWS:SourceArn" = aws_cloudfront_distribution.storage_cdn.arn }
        }
      }
    ]
  })
}

# --- Least-Privilege IAM Policy for the ECS Task Role ---
resource "aws_iam_role_policy" "storage_s3_access" {
  name = "${local.app_name}-storage-s3-access"
  role = aws_iam_role.task_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"]
        Resource = "${aws_s3_bucket.storage.arn}/*"
      },
      {
        Effect   = "Allow"
        Action   = ["s3:ListBucket"]
        Resource = aws_s3_bucket.storage.arn
      }
    ]
  })
}

# --- Outputs ---
output "s3_bucket_name" {
  value = aws_s3_bucket.storage.id
}

output "s3_cdn_domain" {
  value = aws_cloudfront_distribution.storage_cdn.domain_name
}
